# Generated by Django 4.1.1 on 2023-03-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_product_available_date_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='delivery_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliverypoint'),
        ),
    ]
