# Generated by Django 4.1.1 on 2023-03-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_delivery_text_1_delivery_text_2_order_text_1_and_more'),
        ('users', '0004_usercustom_area_alter_usercustom_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliverypoint'),
        ),
    ]
