# Generated by Django 4.1.1 on 2023-05-09 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_usercustom_text_1_usercustom_text_10_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="pin",
            field=models.PositiveIntegerField(
                blank=True,
                default=3239,
                null=True,
                validators=[django.core.validators.MaxValueValidator(9999)],
            ),
        ),
    ]
