# Generated by Django 4.1.1 on 2023-05-12 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_usercustom_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="pin",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(9999)],
            ),
        ),
    ]
