# Generated by Django 4.1.1 on 2023-06-04 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_usercustom_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='pin',
            field=models.PositiveIntegerField(blank=True, default=5930, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
