# Generated by Django 4.1.1 on 2023-03-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_delivery_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='code',
        ),
    ]
