# Generated by Django 4.1.1 on 2023-03-21 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_delivery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='code',
            field=models.CharField(default=uuid.UUID('e58480a7-c891-42a5-b02a-d28bc3ec2e0b'), max_length=255),
        ),
    ]
