# Generated by Django 4.1.1 on 2023-03-21 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_delivery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='code',
            field=models.CharField(default=uuid.UUID('216b1530-b156-47ee-b40b-15971929d970'), max_length=255),
        ),
    ]
