# Generated by Django 4.1.1 on 2023-03-21 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_delivery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='code',
            field=models.CharField(default=uuid.UUID('0178ed52-6672-4c72-81b9-876255db7388'), max_length=255),
        ),
    ]
