# Generated by Django 4.1.1 on 2023-03-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_delivery_code_delivery_delivery_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_code',
        ),
        migrations.AddField(
            model_name='delivery',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
