# Generated by Django 4.1.1 on 2023-03-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_delivery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='estimated_delivery_date',
            field=models.DateField(),
        ),
    ]
