# Generated by Django 4.1.1 on 2023-03-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_delivery_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Dispatched', 'Dispatched'), ('Delivered To Point', 'Delivered To Point'), ('Cancelled', 'Cancelled'), ('Postponed', 'Postponed')], default='Pending', max_length=20),
        ),
    ]
