# Generated by Django 4.1.1 on 2023-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_delivery_code_alter_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='postpone',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='claims',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
