# Generated by Django 4.1.1 on 2023-03-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_delivery_cancelled_remove_delivery_postpone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category_2', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
