# Generated by Django 4.1.1 on 2023-03-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_delivery_city_delivery_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
