# Generated by Django 4.1.1 on 2023-03-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_remove_orderitem_amount_remove_orderitem_min_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='min_price',
        ),
    ]
