# Generated by Django 4.1.1 on 2023-03-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_orderitem_delivery_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
