# Generated by Django 4.1.1 on 2023-03-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_deliverypoint_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='sales_number',
        ),
    ]
