# Generated by Django 4.1.1 on 2023-03-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_remove_delivery_sales_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.delivery'),
        ),
    ]
