# Generated by Django 4.1.1 on 2023-03-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_orderitem_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery',
        ),
    ]
