# Generated by Django 4.1.1 on 2023-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_orderitem_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='estimated_delivery_date',
            field=models.DateField(null=True),
        ),
    ]
