# Generated by Django 4.1.1 on 2023-03-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_orderitem_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='estimated_delivery_date',
            field=models.DateField(),
        ),
    ]
