# Generated by Django 4.1.1 on 2023-03-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_alter_orderitem_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
