# Generated by Django 4.1.1 on 2023-03-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
