# Generated by Django 4.1.1 on 2023-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_orderitem_area_orderitem_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_point_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
