# Generated by Django 4.1.1 on 2023-03-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_orderitem_delivery_point_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_point_name',
        ),
    ]
