# Generated by Django 4.1.1 on 2023-03-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_delivery_status_message_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelleed', 'Cancelled'), ('Delivered', 'Delivered'), ('Ready', 'Ready'), ('Postponed', 'Postponed'), ('Dispatched', 'Dispatched')], default='Ready', max_length=50, null=True),
        ),
    ]
