# Generated by Django 4.1.1 on 2023-05-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0058_cart_text_10_cart_text_11_cart_text_12_cart_text_13_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
