# Generated by Django 4.1.1 on 2023-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='marked_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
